[package]
name = "domainlens"
version = "0.1.0"
edition = "2024"

[dependencies]
cedarwood = { version = "0.4.6" }

[dev-dependencies]
criterion = "0.8.1"
sysinfo = "0.38.0"

[[bench]]
name = "domain_rule_bench"
harness = false